site_name: A/B testing Playbook
theme: 
  name: material
  custom_dir: docs/overrides

  features:
    - navigation.tabs
    - navigation.instant
    - navigation.tracking
    - navigation.indexes
    - navigation.top
    - navigation.footer
    - header.autohide
    - content.action.edit
    #- content.tabs.link #Insiders only so far
    - content.code.annotate
    # - navigation.tabs
    # - announce.dismiss
    # - content.action.edit
    # - content.action.view
    # - content.code.annotate
    # - content.code.copy
    # # - content.tabs.link
    # - content.tooltips
    # # - header.autohide
    # # - navigation.expand
    # - navigation.footer
    # - navigation.indexes
    # # - navigation.instant
    # # - navigation.prune
    # - navigation.sections
    # - navigation.tabs
    # # - navigation.tabs.sticky
    # - navigation.top
    # - navigation.tracking
    # - search.highlight
    # - search.share
    # - search.suggest
    # - toc.follow
    # # - toc.integrate
  language: en
  palette:
    - primary: white
  # - scheme: white
  #   toggle:
  #     icon: material/toggle-switch-off-outline 
  #     name: Switch to dark mode
  #   primary: indigo
  #   accent: indigo 
  # - scheme: slate 
  #   toggle:
  #     icon: material/toggle-switch
  #     name: Switch to light mode    
  #   primary: indigo
  #   accent: blue

  include_sidebar: true

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

extra_css:
  - stylesheets/extra.css


# Page tree
nav:
  - Home: index.md
  - Book: 
    - Intro to A/B testing: "chapter_0/casual_inference.md"
    - Introduction to P-values: 
        - Overview : "chapter_1/chapter_1_overview.md"
        - The p-value: "chapter_1/p_value.md"
    - Probability: "chapter_1/probability.md"
    - What's this about: home.md
    - Other stuff: home.md

